modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://marco/Rain should extinguish campfires/issues"

[[mods]]
modId="rsec"
version="${version}"
displayName="Rain should extinguish campfires"
logoFile="icon.png"
authors="restonic4"
description='''

'''

[[dependencies.rsec]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.rsec]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2]"
   ordering="NONE"
   side="BOTH"