modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://marco/Rain should extinguish campfires/issues"

[[mods]]
modId="rsec"
version="${version}"
displayName="Rain should extinguish campfires"
logoFile="icon.png"
authors="restonic4"
description='''

'''

[[dependencies.rsec]]
   modId="forge"
   mandatory=true
   versionRange="[47,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.rsec]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1]"
   ordering="NONE"
   side="BOTH"
[[dependencies.rsec]]
   modId="restapi"
   mandatory=true
   versionRange="[0.9-1.20.1-Forge]"
   ordering="NONE"
   side="BOTH"
